#pragma namespace("root/cimv2")

#pragma include ("OMC_RegisteredSMIProfile.mof")
#pragma include ("OMC_RegisteredSMISubProfile.mof")
#pragma include ("OMC_ElementConformsToSMIProfile.mof")
#pragma include ("OMC_SMISubProfileRequiresProfile.mof")
#pragma include ("OMC_SMIArraySoftware.mof")
#pragma include ("OMC_SMIVolumeManagementSoftware.mof")
#pragma include ("OMC_SMIElementSoftwareIdentity.mof")

#pragma include ("OMC_StorageConfigurationService.mof")
#pragma include ("OMC_StoragePool.mof")
#pragma include ("OMC_LogicalDisk.mof")
#pragma include ("OMC_StorageVolume.mof")
#pragma include ("OMC_StorageExtent.mof")
#pragma include ("OMC_AllocatedFromStoragePool.mof")
#pragma include ("OMC_BasedOn.mof")
#pragma include ("OMC_CompositeExtent.mof")
#pragma include ("OMC_CompositeExtentBasedOn.mof")
#pragma include ("OMC_HostedStorageConfigurationService.mof")
#pragma include ("OMC_HostedStoragePool.mof")
#pragma include ("OMC_LogicalDiskDevice.mof")
#pragma include ("OMC_StorageCapabilities.mof")
#pragma include ("OMC_StorageConfigurationCapabilities.mof")
#pragma include ("OMC_StorageConfigurationElementCapabilities.mof")
#pragma include ("OMC_StorageElementCapabilities.mof")
#pragma include ("OMC_StorageElementSettingData.mof")
#pragma include ("OMC_StorageSettingWithHints.mof")
#pragma include ("OMC_StorageSettingsGeneratedFromCapabilities.mof")
#pragma include ("OMC_StorageVolumeDevice.mof")
#pragma include ("OMC_SystemStorageCapabilities.mof")
#pragma include ("OMC_AssociatedComponentExtent.mof")
#pragma include ("OMC_AssociatedRemainingExtent.mof")

#pragma include ("OMC_StorageReplicationCapabilities.mof")
#pragma include ("OMC_StorageVolumeStorageSynchronized.mof")
#pragma include ("OMC_LogicalDiskStorageSynchronized.mof")
#pragma include ("OMC_StorageReplicationElementCapabilities.mof")



#pragma namespace("root/interop")
#pragma include ("OMC_RegisteredSMIProfile.mof")
#pragma include ("OMC_RegisteredSMISubProfile.mof")
#pragma include ("OMC_ElementConformsToSMIProfile.mof")
#pragma include ("OMC_SMISubProfileRequiresProfile.mof")
#pragma include ("OMC_SMIArraySoftware.mof")
#pragma include ("OMC_SMIVolumeManagementSoftware.mof")
#pragma include ("OMC_SMIElementSoftwareIdentity.mof")
