/*******************************************************************************
 |
 | 	SMIS-Providers
 | 	Copyright (c) [2008] Novell, Inc.
 | 	All rights reserved. 
 |
 | This program and the accompanying materials
 | are made available under the terms of the Eclipse Public License v1.0
 | which accompanies this distribution, and is available at
 | http://www.eclipse.org/legal/epl-v10.html 
 |
 |********************************************************************************/
//  OMC_SMIElementSoftwareIdentity
// ==========================================================================
[Association, Version ("0.1.0"), Description (
       "The OMC_ElementSoftwareIdentity association defines the "
       "SoftwareIdentity to which the referenced RegisteredProfile/Subprofile is "
       "dependent."),

	Provider("cmpi:omc_smi_server") 
]

class OMC_SMIElementSoftwareIdentity : CIM_ElementSoftwareIdentity 
{
      [Override ( "Antecedent" ), 
       Description ( "A LogicalElement\'s Software Asset." )]
   CIM_SoftwareIdentity REF Antecedent;

      [Override ( "Dependent" ), 
       Description (
          "The ManagedElement that requires or uses the software." )]
   CIM_ManagedElement REF Dependent;
};
	  	
